// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CancelOrderCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsCancelOrderCommand(buf []byte, offset flatbuffers.UOffsetT) *CancelOrderCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CancelOrderCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishCancelOrderCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCancelOrderCommand(buf []byte, offset flatbuffers.UOffsetT) *CancelOrderCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CancelOrderCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCancelOrderCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CancelOrderCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CancelOrderCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CancelOrderCommand) OrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CancelOrderCommand) Pair() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CancelOrderCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CancelOrderCommandAddOrderId(builder *flatbuffers.Builder, orderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(orderId), 0)
}
func CancelOrderCommandAddPair(builder *flatbuffers.Builder, pair flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(pair), 0)
}
func CancelOrderCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
