// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ControlAck struct {
	_tab flatbuffers.Table
}

func GetRootAsControlAck(buf []byte, offset flatbuffers.UOffsetT) *ControlAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ControlAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishControlAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsControlAck(buf []byte, offset flatbuffers.UOffsetT) *ControlAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ControlAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedControlAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ControlAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ControlAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ControlAck) Accepted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ControlAck) MutateAccepted(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ControlAck) SequenceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ControlAck) MutateSequenceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ControlAck) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ControlAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ControlAckAddAccepted(builder *flatbuffers.Builder, accepted bool) {
	builder.PrependBoolSlot(0, accepted, false)
}
func ControlAckAddSequenceId(builder *flatbuffers.Builder, sequenceId uint64) {
	builder.PrependUint64Slot(1, sequenceId, 0)
}
func ControlAckAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(reason), 0)
}
func ControlAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
