// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlwire

import "strconv"

type ControlPayload byte

const (
	ControlPayloadNONE               ControlPayload = 0
	ControlPayloadCancelOrderCommand ControlPayload = 1
	ControlPayloadReplayRequest      ControlPayload = 2
	ControlPayloadSnapshotRequest    ControlPayload = 3
	ControlPayloadControlAck         ControlPayload = 4
)

var EnumNamesControlPayload = map[ControlPayload]string{
	ControlPayloadNONE:               "NONE",
	ControlPayloadCancelOrderCommand: "CancelOrderCommand",
	ControlPayloadReplayRequest:      "ReplayRequest",
	ControlPayloadSnapshotRequest:    "SnapshotRequest",
	ControlPayloadControlAck:         "ControlAck",
}

var EnumValuesControlPayload = map[string]ControlPayload{
	"NONE":               ControlPayloadNONE,
	"CancelOrderCommand": ControlPayloadCancelOrderCommand,
	"ReplayRequest":      ControlPayloadReplayRequest,
	"SnapshotRequest":    ControlPayloadSnapshotRequest,
	"ControlAck":         ControlPayloadControlAck,
}

func (v ControlPayload) String() string {
	if s, ok := EnumNamesControlPayload[v]; ok {
		return s
	}
	return "ControlPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
