// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ControlEnvelope struct {
	_tab flatbuffers.Table
}

const ControlEnvelopeIdentifier = "LOCT"

func GetRootAsControlEnvelope(buf []byte, offset flatbuffers.UOffsetT) *ControlEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ControlEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishControlEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ControlEnvelopeIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func ControlEnvelopeBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, ControlEnvelopeIdentifier)
}

func GetSizePrefixedRootAsControlEnvelope(buf []byte, offset flatbuffers.UOffsetT) *ControlEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ControlEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedControlEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(ControlEnvelopeIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedControlEnvelopeBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, ControlEnvelopeIdentifier)
}

func (rcv *ControlEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ControlEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ControlEnvelope) CommandId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ControlEnvelope) TimestampNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ControlEnvelope) MutateTimestampNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ControlEnvelope) PayloadType() ControlPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return ControlPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ControlEnvelope) MutatePayloadType(n ControlPayload) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *ControlEnvelope) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ControlEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ControlEnvelopeAddCommandId(builder *flatbuffers.Builder, commandId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(commandId), 0)
}
func ControlEnvelopeAddTimestampNs(builder *flatbuffers.Builder, timestampNs uint64) {
	builder.PrependUint64Slot(1, timestampNs, 0)
}
func ControlEnvelopeAddPayloadType(builder *flatbuffers.Builder, payloadType ControlPayload) {
	builder.PrependByteSlot(2, byte(payloadType), 0)
}
func ControlEnvelopeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func ControlEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
