// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReplayRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsReplayRequest(buf []byte, offset flatbuffers.UOffsetT) *ReplayRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReplayRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishReplayRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReplayRequest(buf []byte, offset flatbuffers.UOffsetT) *ReplayRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReplayRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReplayRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReplayRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReplayRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReplayRequest) Pair() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReplayRequest) FromSequenceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReplayRequest) MutateFromSequenceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ReplayRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReplayRequestAddPair(builder *flatbuffers.Builder, pair flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pair), 0)
}
func ReplayRequestAddFromSequenceId(builder *flatbuffers.Builder, fromSequenceId uint64) {
	builder.PrependUint64Slot(1, fromSequenceId, 0)
}
func ReplayRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
