// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tradingwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderStatusEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderStatusEvent(buf []byte, offset flatbuffers.UOffsetT) *OrderStatusEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderStatusEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderStatusEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderStatusEvent(buf []byte, offset flatbuffers.UOffsetT) *OrderStatusEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderStatusEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderStatusEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderStatusEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderStatusEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderStatusEvent) SequenceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderStatusEvent) MutateSequenceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderStatusEvent) OrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderStatusEvent) Status() OrderStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return OrderStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderStatusEvent) MutateStatus(n OrderStatus) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *OrderStatusEvent) FilledQuantity() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderStatusEvent) MutateFilledQuantity(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *OrderStatusEvent) RemainingQuantity() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderStatusEvent) MutateRemainingQuantity(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *OrderStatusEvent) AvgPrice() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderStatusEvent) MutateAvgPrice(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func OrderStatusEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func OrderStatusEventAddSequenceId(builder *flatbuffers.Builder, sequenceId uint64) {
	builder.PrependUint64Slot(0, sequenceId, 0)
}
func OrderStatusEventAddOrderId(builder *flatbuffers.Builder, orderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(orderId), 0)
}
func OrderStatusEventAddStatus(builder *flatbuffers.Builder, status OrderStatus) {
	builder.PrependByteSlot(2, byte(status), 0)
}
func OrderStatusEventAddFilledQuantity(builder *flatbuffers.Builder, filledQuantity uint64) {
	builder.PrependUint64Slot(3, filledQuantity, 0)
}
func OrderStatusEventAddRemainingQuantity(builder *flatbuffers.Builder, remainingQuantity uint64) {
	builder.PrependUint64Slot(4, remainingQuantity, 0)
}
func OrderStatusEventAddAvgPrice(builder *flatbuffers.Builder, avgPrice uint64) {
	builder.PrependUint64Slot(5, avgPrice, 0)
}
func OrderStatusEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
