// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tradingwire

import "strconv"

type OrderType byte

const (
	OrderTypeLIMIT      OrderType = 0
	OrderTypeMARKET     OrderType = 1
	OrderTypeSTOP_LIMIT OrderType = 2
)

var EnumNamesOrderType = map[OrderType]string{
	OrderTypeLIMIT:      "LIMIT",
	OrderTypeMARKET:     "MARKET",
	OrderTypeSTOP_LIMIT: "STOP_LIMIT",
}

var EnumValuesOrderType = map[string]OrderType{
	"LIMIT":      OrderTypeLIMIT,
	"MARKET":     OrderTypeMARKET,
	"STOP_LIMIT": OrderTypeSTOP_LIMIT,
}

func (v OrderType) String() string {
	if s, ok := EnumNamesOrderType[v]; ok {
		return s
	}
	return "OrderType(" + strconv.FormatInt(int64(v), 10) + ")"
}
