// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tradingwire

import "strconv"

type OrderStatus byte

const (
	OrderStatusOPEN     OrderStatus = 0
	OrderStatusPARTIAL  OrderStatus = 1
	OrderStatusFILLED   OrderStatus = 2
	OrderStatusCANCELED OrderStatus = 3
	OrderStatusREJECTED OrderStatus = 4
)

var EnumNamesOrderStatus = map[OrderStatus]string{
	OrderStatusOPEN:     "OPEN",
	OrderStatusPARTIAL:  "PARTIAL",
	OrderStatusFILLED:   "FILLED",
	OrderStatusCANCELED: "CANCELED",
	OrderStatusREJECTED: "REJECTED",
}

var EnumValuesOrderStatus = map[string]OrderStatus{
	"OPEN":     OrderStatusOPEN,
	"PARTIAL":  OrderStatusPARTIAL,
	"FILLED":   OrderStatusFILLED,
	"CANCELED": OrderStatusCANCELED,
	"REJECTED": OrderStatusREJECTED,
}

func (v OrderStatus) String() string {
	if s, ok := EnumNamesOrderStatus[v]; ok {
		return s
	}
	return "OrderStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
