// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tradingwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderIngress struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderIngress(buf []byte, offset flatbuffers.UOffsetT) *OrderIngress {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderIngress{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderIngressBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderIngress(buf []byte, offset flatbuffers.UOffsetT) *OrderIngress {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderIngress{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderIngressBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderIngress) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderIngress) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderIngress) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderIngress) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderIngress) Pair() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderIngress) Side() OrderSide {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return OrderSide(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderIngress) MutateSide(n OrderSide) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *OrderIngress) OrderType() OrderType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return OrderType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderIngress) MutateOrderType(n OrderType) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *OrderIngress) Price() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderIngress) MutatePrice(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *OrderIngress) Quantity() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderIngress) MutateQuantity(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *OrderIngress) TimeInForce() TimeInForce {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return TimeInForce(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderIngress) MutateTimeInForce(n TimeInForce) bool {
	return rcv._tab.MutateByteSlot(18, byte(n))
}

func (rcv *OrderIngress) PostOnly() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OrderIngress) MutatePostOnly(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *OrderIngress) ReduceOnly() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OrderIngress) MutateReduceOnly(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *OrderIngress) TimestampNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderIngress) MutateTimestampNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func (rcv *OrderIngress) FeeTier() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderIngress) MutateFeeTier(n byte) bool {
	return rcv._tab.MutateByteSlot(26, n)
}

func OrderIngressStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func OrderIngressAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func OrderIngressAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(userId), 0)
}
func OrderIngressAddPair(builder *flatbuffers.Builder, pair flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(pair), 0)
}
func OrderIngressAddSide(builder *flatbuffers.Builder, side OrderSide) {
	builder.PrependByteSlot(3, byte(side), 0)
}
func OrderIngressAddOrderType(builder *flatbuffers.Builder, orderType OrderType) {
	builder.PrependByteSlot(4, byte(orderType), 0)
}
func OrderIngressAddPrice(builder *flatbuffers.Builder, price uint64) {
	builder.PrependUint64Slot(5, price, 0)
}
func OrderIngressAddQuantity(builder *flatbuffers.Builder, quantity uint64) {
	builder.PrependUint64Slot(6, quantity, 0)
}
func OrderIngressAddTimeInForce(builder *flatbuffers.Builder, timeInForce TimeInForce) {
	builder.PrependByteSlot(7, byte(timeInForce), 0)
}
func OrderIngressAddPostOnly(builder *flatbuffers.Builder, postOnly bool) {
	builder.PrependBoolSlot(8, postOnly, false)
}
func OrderIngressAddReduceOnly(builder *flatbuffers.Builder, reduceOnly bool) {
	builder.PrependBoolSlot(9, reduceOnly, false)
}
func OrderIngressAddTimestampNs(builder *flatbuffers.Builder, timestampNs uint64) {
	builder.PrependUint64Slot(10, timestampNs, 0)
}
func OrderIngressAddFeeTier(builder *flatbuffers.Builder, feeTier byte) {
	builder.PrependByteSlot(11, feeTier, 0)
}
func OrderIngressEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
