// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tradingwire

import "strconv"

type OrderSide byte

const (
	OrderSideBUY  OrderSide = 0
	OrderSideSELL OrderSide = 1
)

var EnumNamesOrderSide = map[OrderSide]string{
	OrderSideBUY:  "BUY",
	OrderSideSELL: "SELL",
}

var EnumValuesOrderSide = map[string]OrderSide{
	"BUY":  OrderSideBUY,
	"SELL": OrderSideSELL,
}

func (v OrderSide) String() string {
	if s, ok := EnumNamesOrderSide[v]; ok {
		return s
	}
	return "OrderSide(" + strconv.FormatInt(int64(v), 10) + ")"
}
