// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tradingwire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TradeEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsTradeEvent(buf []byte, offset flatbuffers.UOffsetT) *TradeEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TradeEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishTradeEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTradeEvent(buf []byte, offset flatbuffers.UOffsetT) *TradeEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TradeEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTradeEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TradeEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TradeEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TradeEvent) SequenceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeEvent) MutateSequenceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *TradeEvent) TimestampNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeEvent) MutateTimestampNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TradeEvent) Pair() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TradeEvent) MakerOrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TradeEvent) TakerOrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TradeEvent) MakerUserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TradeEvent) TakerUserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TradeEvent) Price() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeEvent) MutatePrice(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *TradeEvent) Quantity() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeEvent) MutateQuantity(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

func (rcv *TradeEvent) MakerFeeBps() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeEvent) MutateMakerFeeBps(n int16) bool {
	return rcv._tab.MutateInt16Slot(22, n)
}

func (rcv *TradeEvent) TakerFeeBps() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeEvent) MutateTakerFeeBps(n int16) bool {
	return rcv._tab.MutateInt16Slot(24, n)
}

func TradeEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func TradeEventAddSequenceId(builder *flatbuffers.Builder, sequenceId uint64) {
	builder.PrependUint64Slot(0, sequenceId, 0)
}
func TradeEventAddTimestampNs(builder *flatbuffers.Builder, timestampNs uint64) {
	builder.PrependUint64Slot(1, timestampNs, 0)
}
func TradeEventAddPair(builder *flatbuffers.Builder, pair flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(pair), 0)
}
func TradeEventAddMakerOrderId(builder *flatbuffers.Builder, makerOrderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(makerOrderId), 0)
}
func TradeEventAddTakerOrderId(builder *flatbuffers.Builder, takerOrderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(takerOrderId), 0)
}
func TradeEventAddMakerUserId(builder *flatbuffers.Builder, makerUserId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(makerUserId), 0)
}
func TradeEventAddTakerUserId(builder *flatbuffers.Builder, takerUserId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(takerUserId), 0)
}
func TradeEventAddPrice(builder *flatbuffers.Builder, price uint64) {
	builder.PrependUint64Slot(7, price, 0)
}
func TradeEventAddQuantity(builder *flatbuffers.Builder, quantity uint64) {
	builder.PrependUint64Slot(8, quantity, 0)
}
func TradeEventAddMakerFeeBps(builder *flatbuffers.Builder, makerFeeBps int16) {
	builder.PrependInt16Slot(9, makerFeeBps, 0)
}
func TradeEventAddTakerFeeBps(builder *flatbuffers.Builder, takerFeeBps int16) {
	builder.PrependInt16Slot(10, takerFeeBps, 0)
}
func TradeEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
