// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package marketdatawire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderBookLevel struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderBookLevel(buf []byte, offset flatbuffers.UOffsetT) *OrderBookLevel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderBookLevel{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderBookLevelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderBookLevel(buf []byte, offset flatbuffers.UOffsetT) *OrderBookLevel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderBookLevel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderBookLevelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderBookLevel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderBookLevel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderBookLevel) Price() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderBookLevel) MutatePrice(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderBookLevel) Quantity() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderBookLevel) MutateQuantity(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *OrderBookLevel) OrderCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderBookLevel) MutateOrderCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func OrderBookLevelStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func OrderBookLevelAddPrice(builder *flatbuffers.Builder, price uint64) {
	builder.PrependUint64Slot(0, price, 0)
}
func OrderBookLevelAddQuantity(builder *flatbuffers.Builder, quantity uint64) {
	builder.PrependUint64Slot(1, quantity, 0)
}
func OrderBookLevelAddOrderCount(builder *flatbuffers.Builder, orderCount uint32) {
	builder.PrependUint32Slot(2, orderCount, 0)
}
func OrderBookLevelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
