// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package marketdatawire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderBookSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderBookSnapshot(buf []byte, offset flatbuffers.UOffsetT) *OrderBookSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderBookSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderBookSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderBookSnapshot(buf []byte, offset flatbuffers.UOffsetT) *OrderBookSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderBookSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderBookSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderBookSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderBookSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderBookSnapshot) SequenceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderBookSnapshot) MutateSequenceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderBookSnapshot) TimestampNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderBookSnapshot) MutateTimestampNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *OrderBookSnapshot) Pair() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderBookSnapshot) Bids(obj *OrderBookLevel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OrderBookSnapshot) BidsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *OrderBookSnapshot) Asks(obj *OrderBookLevel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OrderBookSnapshot) AsksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func OrderBookSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func OrderBookSnapshotAddSequenceId(builder *flatbuffers.Builder, sequenceId uint64) {
	builder.PrependUint64Slot(0, sequenceId, 0)
}
func OrderBookSnapshotAddTimestampNs(builder *flatbuffers.Builder, timestampNs uint64) {
	builder.PrependUint64Slot(1, timestampNs, 0)
}
func OrderBookSnapshotAddPair(builder *flatbuffers.Builder, pair flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(pair), 0)
}
func OrderBookSnapshotAddBids(builder *flatbuffers.Builder, bids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(bids), 0)
}
func OrderBookSnapshotStartBidsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func OrderBookSnapshotAddAsks(builder *flatbuffers.Builder, asks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(asks), 0)
}
func OrderBookSnapshotStartAsksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func OrderBookSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
